### ISSUE TITLE
node.js app tries connecting to localhost on openshift

### ISSUE THREAD

**Issue by sbose78** [nodeshift-starters/nodejs-rest-http-crud#118]
When the nodejs CRUD booster is imported into the ${username}-stage namespace of openshift online ( cluster 2a). It turns out that the app is unable to communicate with the DB. The pod logs indicate that the app tries talking to localhost https://github.com/nodeshift-starters/nodejs-rest-http-crud/blob/c107730ad9add33d85e3e58bd006979d736584c6/lib/db/index.js#L5

This needs to be fixed such that the app talks to the DB service.

Being tracked for the upcoming sprint https://openshift.io/openshiftio/Openshift_io/plan/detail/1331

**Comment by jarifibrahim** [comment]
The app can talk to the DB service. The only limitation right now is that the DB service's name should be `my-database`. When the DB service's name is `my-database` then the variable `MY_DATABASE_SERVICE_HOST` holds the I.P. Address of the DB service and the main app can then communicate with the database.

**Comment by sbose78** [comment]
Interestingly, I see this issue on cluster us-east-2a and not on us-east-1b

**Comment by jarifibrahim** [comment]
> > When the DB service's name is my-database then the variable MY_DATABASE_SERVICE_HOST holds the I.P. Address of the DB service
> 
> How does this happen?

This is a Kubernetes (openshift) thing https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services

When you have a service called `foo` then the environment variable `FOO_SERVICE_HOST` holds the IP address of the node on which the service is running. The openshift/kubernetes DNS resolves the service name into IP address.

**Comment by lholmquist** [comment]
can this be closed?  It doesn't seem like the issue is this boosters, but the environment it is run?

**Comment by sbose78** [comment]
Thanks @jarifibrahim ! Didn't find that in the openshift docs :)

@akashshinde 
As a workaround, point your `MY_DATABASE_SERVICE_HOST` env var to something like `my-database.shbose-stage.svc` which is the service's hostname, and do a rebuild.

**Comment by sbose78** [comment]
Sure closing this, @lholmquist .

**Comment by akashshinde** [comment]
@sbose78  It seems there is a communication issue or network restriction when we deploy application under `non-stage/non-run` env, Deploying under stage/run works properly.
