### ISSUE TITLE
Application doesn't appear to connect to the database when deployed to the Sandbox

### ISSUE THREAD

**Issue by BethGriggs** [nodeshift-starters/nodejs-rest-http-crud#365]
Per title - following the instructions in the README I cannot get the application to talk to the database when deployed to the sandbox.

**Comment by helio-frota** [comment]
@BethGriggs thanks for reporting this :+1: 

@pnaik1 after you login on https://developers.redhat.com/developer-sandbox

You can click in your username and then copy the login command

![foo](https://user-images.githubusercontent.com/6443576/190015374-e7092a0c-87e5-40a3-bf86-e242b948eec4.png)

And paste in your terminal to login in the sandbox instead of OpenShift local :+1:

**Comment by pnaik1** [comment]
okay, Thanks

**Comment by pnaik1** [comment]
@BethGriggs, I went through the instruction and deployed it on sandbox , In my case the database is connected to the application ... 
To check that I have tried running this command in the database terminal 
sh-4.2$ psql -U luke -d my_data
psql (10.17)
Type "help" for help.

my_data=> \dt
         List of relations
 Schema |   Name   | Type  | Owner 
--------+----------+-------+-------
 public | products | table | luke
(1 row)

my_data=> select * from products;
 id |  name  | stock 
----+--------+-------
  1 | Apple  |    10
  2 | Orange |    10
  3 | Pear   |    10
(3 rows)

**Comment by helio-frota** [comment]
yeah I can confirm

![555](https://user-images.githubusercontent.com/6443576/190354937-0aa6e31a-584c-403d-a961-08b4e11bb7c7.png)

I think we can close this issue.

Thanks @BethGriggs and @pnaik1

**Comment by helio-frota** [comment]
> Interesting, so you were able to add/remove/get the items from the db via the web application?

yeah :+1: 

> My issue was the Node.js app wasn't bound/connected to the db - just want to confirm that part is fixed?

yeah that is connecting using the sandbox. Maybe you had issue/glitches on sandbox itself at the moment you tried ?
